config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :spots, only: %i[index show new] do
    resources :pages, only: %i[index new]
  end

  resources :alerts, only: %i[new create]
end

app/models/alert.rb
class Alert < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :weathers, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  before_destroy :destroy_photos

  def distance_between(address_lat, address_long)
    Geocoder::Calculations.distance_between([address_lat, address_long], [latitude, longitude]).round(0)
  end

  def weathers_filtered_by_time(weather_ids_only_time)
    weathers.where(id: weather_ids_only_time)
  end

  def weathers_filtered(weathers_filtered)
    weathers.where(id: weathers_filtered)
  end

  private

  def geocode
    # Initially just call the original method as intended.
    super

    # Check to see if geocoding failed.
    return unless latitude.blank? && longitude.blank?

    postal_code = address.scan(/\d{5}/).first
    geocode = Geocoder.search(postal_code).find { |r| r.data["address"]["country_code"] == "fr" }
    self.longitude = geocode.coordinates[1] if geocode
    self.latitude = geocode.coordinates[0] if geocode
  end

  def destroy_photos
    photos.purge
  end
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :spot
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  def new
    @alert = Alert.new
  end

  def create
    @alert = Alert.new(alert_params)
    return unless @alert.save!

    SendAlertJob.new(@alert.id, "welcome").perform_now
    redirect_back(fallback_location: spots_path)
    # on crée une seule alerte avec les params récupérer via le formulaire de l'index et si on arrive a save on redirige vers la même page (redirect_back) pour conserver les params rentrés dans la page homes pour la liste d'index
  end

  private

  def alert_params
    params.require(:alert).permit(:difficulty, :wind_min, :wind_max, :time, :address, :perimeter, :telephone_number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @spots = Spot.all
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  require 'date'
  def new
    @spot = Spot.new
  end

  def create
  end

  def index
    geocode = Geocoder.search(params[:address]).find { |r| r.data["address"]["country_code"] == "fr" }
    @address_lat = geocode.coordinates[0]
    @address_long = geocode.coordinates[1]
    results = FilterSpotsService.new(params[:difficulty], params[:wind_min], params[:wind_max], params[:time], @address_lat, @address_long, params[:perimeter]).call
    @spots = results[:spots]
    # tous les spots filtrés
    @weathers = results[:weathers]
    # toutes les weathers filtrées
    cookies[:weather_ids] = results[:weather_ids].split("&")
    # on stock les weathers filtrés dans les cookies pour pouvoir les récupérer
    cookies[:weather_ids_only_time] = results[:weather_ids_only_time]
    # On stock toutes les weathers juste filtrée par time
  end

  def show
    @spot = Spot.find(params[:id])
    # @weathers = @spot.weathers.where(id: params[:weather_ids].split(" ")) if params[:weather_ids].present?
    unless params[:from_home].present?
      @good_weathers = @spot.weathers_filtered(cookies[:weather_ids].gsub('[', "").gsub("]", "").split(", ").map(&:to_i))
      @weathers = @spot.weathers_filtered_by_time(cookies[:weather_ids_only_time].split("&"))
    end
    # tous les weathers filtré par le time
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :address, :description, photos: [])
  end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  def new
    @weather = Weather.new
  end

  def create
  end

  def update
    @weathers = Weather.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_well_time(time)
    "#{time.hour}h"
  end

  def criteria_correspond?(weather)
    cookies[:weather_ids].gsub('[', "").gsub("]", "").split(", ").map(&:to_i).include?(weather.id)
  end

  def difficulty_level(spot_difficulty)
    case spot_difficulty
    when "Débutant"
      "level-beginning"
    when "Intermédiaire"
      "level-intermediate"
    when "Confirmé"
      "level-confirm"
    when "Expert"
      "level-expert"
    end
  end

  def first_good_weather_direction(spot)
    spot.weathers.where(id: cookies[:weather_ids_only_time]).first.wind_direction
  end

  def translate_day(day)
    trad_hash = {
      monday: "Lundi",
      tuesday: "Mardi",
      wednesday: "Mercredi",
      thursday: "Jeudi",
      friday: "Vendredi",
      saturday: "Samedi",
      sunday: "Sunday"

    }
    trad_hash[day.downcase.to_sym]
  end

  def translate_month(month)
    trad_hash = {
      january: "Janvier",
      february: "Février",
      march: "Mars",
      april: "Avril",
      may: "Mai",
      june: "Juin",
      july: "Juillet",
      august: "Août",
      september: "Septembre",
      october: "Octobre",
      november: "Novembre",
      december: "Décembre"
    }
    trad_hash[month.downcase.to_sym]
  end
end

app/views/alerts/_form.html.erb
  <%= form_with model: Alert.new do |f| %>
    <%# Alert.new permet à form_with de créer la route vers la méthode create de Alert car Alert ne passède pas de page et de méthode new et parce que la méthode create est appelée sur l'index des spots  %>
    <%= f.hidden_field :difficulty, value: params[:difficulty] %>
    <%= f.hidden_field :wind_min, value: params[:wind_min] %>
    <%= f.hidden_field :wind_max, value: params[:wind_max] %>
    <%= f.hidden_field :time, value: params[:time] %>
    <%= f.hidden_field :address, value: params[:address] %>
    <%= f.hidden_field :perimeter, value: params[:perimeter] %>
    <%= f.telephone_field :telephone_number, placeholder: "Ex: 06.xx.xx.xx.xx", style: "margin-bottom: 1rem;", class: "inputField" %>
    <%# hidden_field permet de cacher le champs du formualire et on lui passe en value la params contenu dans l'url %>
    <button type="submit" class="button-alert" >
      <i class="fa fa-bell fa-shake"></i>
      Notifier
    </button>
  <% end %>

app/views/alerts/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <div data-controller="modal">
    <div class="blur"></div>
    <div class="modal-container">
      <h3>Créer une notification SMS</h3>
      <%= render 'form', alert: @alert %>
      <div data-action="click->modal#closeModal"><i class="fa-solid fa-square-xmark fa-xl"></i></div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WindCall</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="Grâce à Wind'Call, vous allez pouvoir trouver les meilleurs spots de Kite Surf en fonction de vos propres critères !">
    <meta property="og:title" content="Wind'Call - Le meilleur site pour les Kites Surfers !">
    <meta property="og:image" content="picto.jpg">
    <meta property="og:site_name" content="Wind'Call"/>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">

    <%= render 'shared/ios_pwa_links' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
     <main>
        <%= yield %>
     </main>
    <%= turbo_frame_tag "modal" %>
    <%# <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<%# <%= render 'shared/navbar' %>
<div class="header">
  <h1 class="title">Wind'Call</h1>
  <a href="#start-direction" class="home-button"> Let's go</a>
</div>

<div class="container" id="start-direction">
<h2>Trouve ton prochain spot de Kite Surf !</h2>
<p>Découvre les plus beaux spots de Kite
Surf en fonction de tes critères  à travers
la France !</p>

<%= form_with url: spots_path, method: "get", data: { controller: "double-slider"} do |f| %>
  <div class="choose-difficulty-spot" data-controller="filter">
  <p>Séléctionne la difficulté de ton spot</p>

    <%#= desolé jean ro %>
    <div class="first-two-div">
      <%#= f.check_box "difficulty[]", id: "deb", input_html: {value: "deb"} %>
      <div>
        <input type="checkbox" name="difficulty[]" value="Débutant" id="deb" data-action="change->filter#selectFilter">
        <label class="difficulty-spot", for="deb">
          <%= image_tag "tadpole.png", class:"css-logo-button"%>
        <div id="logo-button">
          <p>Débutant</p>
        </div>
        </label>
      </div>

      <div>
        <%#= f.check_box :difficulty, id: "int" %>
        <input type="checkbox" name="difficulty[]" value="Intermédiaire" id="int"  data-action="change->filter#selectFilter">
        <label class="difficulty-spot", for="int">
          <%= image_tag "fish.png", class:"css-logo-button"%>
        <div id="logo-button">
          <p>Intermédiaire</p>
        </div>
      </div>
    </div>

    <div class="two-last-div">
      <%#= f.check_box :difficulty, id: "con" %>
      <div>
        <input type="checkbox" name="difficulty[]" value="Confirmé" id="con"  data-action="change->filter#selectFilter">
        <label class="difficulty-spot", for="con">
          <%= image_tag "dolphin.png", class:"css-logo-button"%>
        <div id="logo-button">
          <p>Confirmé</p>
        </div>
        </label>
      </div>

      <%#= f.check_box :difficulty, id: "exp" %>
      <div>
        <input type="checkbox" name="difficulty[]" value="Expert" id="exp"  data-action="change->filter#selectFilter">
        <label class="difficulty-spot", for="exp">
          <%= image_tag "shark.png", class:"css-logo-button"%>
        <div id="logo-button">
          <p>Expert</p>
        </div>
      </div>
    </div>
  </div>

  <p>Selectionne la force du vent ! (en noeuds)</p>

  <div class="double-slider">
    <span class="value" data-double-slider-target="rangeOne"></span>
    <div class="slider-container">
      <div data-double-slider-target="sliderBar" class="slider-bar"></div>
      <%= f.range_field :wind_min, value: params[:wind_min] || "15", min: "0", max: "60", data: { double_slider_target: "sliderOne", action: "input->double-slider#slideOne"} %>
      <%= f.range_field :wind_max, value: params[:wind_max] || "30", min: "0", max: "60", data: { double_slider_target: "sliderTwo", action: "input->double-slider#slideTwo"} %>
    </div>
    <span class="value" data-double-slider-target="rangeTwo"></span>

  </div>

  <p>Quand veux-tu aller Kite-Surfer ?</p>

    <div class="first-two-div">
      <%= f.radio_button :time, "Today", id: "today" %>
      <%= f.label :time, "Aujourd'hui", class:"when-kite-spot", for: "today" %>

      <%= f.radio_button :time, "Tomorrow", id: "tomorrow" %>
      <%= f.label :time, "Demain", class:"when-kite-spot", for: "tomorrow" %>

      <%= f.radio_button :time, "After", id: "after" %>
      <%= f.label :time, "Après-demain", class:"when-kite-spot", for: "after" %>
    </div>
    <div class="form-geolocation">
      <div data-controller="address-autocomplete" id="map-search"
           data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
        <%= f.text_field :address, data: {address_autocomplete_target: "address"},
        style: "display:none;"
        %>
      </div>
      <%= f.text_field :perimeter, placeholder: "Ton périmètre !" %>
    </div>

  <div class="submit-button">
    <%= f.button "Valide tes critères !", class:"button-link-to" %>
  </div>
<% end %>

<div class="begin-caroussel">
  <p>Teste de tout nouveaux spots !</p>
</div>
<section class="carousel" aria-label="Gallery">
  <ol class="carousel__viewport">
    <% @spots.sample(5).each do |spot| %>
      <li id="carousel__slide1"
        tabindex="0"
        class="carousel__slide">
        <div class="carousel__snapper" style="background-image:url(<%= spot.photos.first.url %>)" id="first-carousel">
          <div class="div-container-h3">
            <h3><%= spot.name %></h3>
          </div>
          <a href="#carousel__slide4"></a>
          <a href="#carousel__slide2"></a>
        </div>
        <%= link_to "", spot_path(spot, from_home: "true"), class: "carousel_link" %>
      </li>
    <% end %>
  </ol>
</section>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <%# <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div> %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_navbar.html.erb
<nav class="navbar">
      <%= link_to root_path do %>
  <%= image_tag "picto.png", class:"logo"%>
    <% end %>
</nav>

app/views/spots/index.html.erb
<%= render 'shared/navbar' %>
<div data-controller="loading" class="container loading">
  <div class="dots-loader"></div>
  <div class="spot-cards">
    <% if @spots.present? %>
      <%= link_to new_alert_path(params: request.params), data: { turbo_frame: "modal" }, class: "button-alert" do %>
          <i class="fa fa-bell fa-shake"></i>
          <span>Alerte</span>
      <% end %>
      <% @spots.each do |spot| %>
        <%= link_to spot_path(spot), class:"card-trip" do %>
          <% if spot.photos.attached? %>
              <%= cl_image_tag spot.photos.first.key %>
            <% else %>
              <img src="http://image.noelshack.com/fichiers/2022/48/3/1669826426-image-processing20200111-22153-1bi0cow.jpg">
            <% end %>
          <div class="card-trip-infos">
            <h2><%= spot.name %></h2>
            <h2> à <%= spot.distance_between(@address_lat, @address_long) %> km</h2>
          </div>
          <div class="card-trip-pricing">
            <div class="winds-logo">
              <p><%= image_tag "vent.png", class: "wind-logo" %></p>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="normal-h", style= "rotate: <%= first_good_weather_direction(spot) %>deg;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5L12 3m0 0l7.5 7.5M12 3v18" />
              </svg>
            </div>
            <div class="difficulty-logo">
              <div class="<%= difficulty_level(spot.difficulty)%>"></div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>

    <div class="oups">
      <p class="sorry"><span>Oh oh...</span> Il n'y a pas de résultats qui correspondent à tes critères !</p>
      <%= link_to "Refais une recherche !", root_path, class: "submit-button"  %>
      <% end %>

      <div class="pouf">
      <p class="sorry">...ou crée une Alerte</p>
        <%= link_to new_alert_path(params: request.params), data: { turbo_frame: "modal" }, class: "button-alert" do %>
            <i class="fa fa-bell fa-shake"></i>
            <span>Crée une alerte</span>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spots/show.html.erb
<div class="contenair-show">

  <section class="carousel show" aria-label="Gallery">

    <div class="spot-icons">
      <%= link_to :back do %>
        <i class='far fa-arrow-alt-circle-left' style='font-size:24px'></i>
      <% end %>
      <%= link_to :root do %>
        <i class="fa-solid fa-house" style='font-size:24px'></i>
      <% end %>
      <div class="spot-heart">
        <input id="heart" type="checkbox" />
        <label for="heart"><i class="fa-solid fa-heart"></i></label>
      </div>
    </div>

    <div class="spot-infos">
      <h3><%= @spot.name %></h3>
      <h3><%= @spot.address %></h3>
    </div>
    <ol class="carousel__viewport show">
      <% @spot.photos.each do |photo| %>
        <li id="carousel__slide1"
          tabindex="0"
          class="carousel__slide">
          <div class="carousel__snapper show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path photo.key %>')" id="first-carousel">
          </div>
        </li>
      <% end %>
    </ol>
  </section>

  <% if @weathers.present? %>
    <div class="fullDate">
      <p>
        <%= translate_day(@weathers.first.time.strftime("%A")) %>
        <%= @weathers.first.time.strftime("%d")%>
        <%= translate_month(@weathers.first.time.strftime("%B")) %>
      </p>
    </div>

    <div data-controller="table">

      <table class="weather-card" data-table-target="goodWeathers" >
        <thead>
          <tr class="head-table">
            <th>Heure</th>
            <th>Vent</th>
            <th>Rafale</th>
            <th>Pluie</th>
            <th>Air</th>
          </tr>
        </thead>
          <tbody>
            <% @good_weathers.first(3).each do |weather| %>
            <tr class="table-element colored">
              <td class="time">
                <%= display_well_time(weather.time) %>
              </td>
              <td class="wind">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="normal-h", style= "rotate: <%= weather.wind_direction %>deg;">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5L12 3m0 0l7.5 7.5M12 3v18" />
                </svg>
                <%= weather.wind_force.to_i %>nd
              </td>
              <td class="wind-gust time">
                <i class="fa-solid fa-tornado"></i>
                <%= weather.gust_wind %>nd
              </td>
              <td class="rain time">
                <i class="fa-solid fa-droplet"></i>
                <%= weather.prob_rain %>%
              </td>
              <td class="temperature time">
                <i class="fa-solid fa-temperature-three-quarters"></i>
                <%= weather.temperature %>°C
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>

      <table id="voir-plus" class="weather-card hidden" data-table-target="allWeathers">
        <thead>
          <tr class="head-table">
            <th>Heure</th>
            <th>Vent</th>
            <th>Rafale</th>
            <th>Pluie</th>
            <th>Air</th>
          </tr>
        </thead>
          <tbody>
            <% @weathers.each do |weather| %>
            <tr class="table-element <%= 'colored' if criteria_correspond?(weather) %>">
              <td class="time">
                <%= display_well_time(weather.time) %>
              </td>
              <td class="wind">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="normal-h", style= "rotate: <%= weather.wind_direction %>deg;">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5L12 3m0 0l7.5 7.5M12 3v18" />
                </svg>
                <%= weather.wind_force.to_i %>nd
              </td>
              <td class="wind-gust time">
                <i class="fa-solid fa-tornado"></i>
                <%= weather.gust_wind %>nd
              </td>
              <td class="rain time">
                <i class="fa-solid fa-droplet"></i>
                <%= weather.prob_rain %>%
              </td>
              <td class="temperature time">
                <i class="fa-solid fa-temperature-three-quarters"></i>
                <%= weather.temperature %>°C
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>
      <a href="#voir-plus">
        <button class="allInfos" data-action="click->table#changeTable">Voir plus</button>
      </a>
    </div>

    <div class="map">

      <%= cl_image_tag @spot.photos.last.key, class:"show-map" %>
      <p><%= image_tag "arrow-up.png", class: "arrow-map", style: "rotate: #{@good_weathers.first.wind_direction}deg;" %></p>
    </div>
  <% end %>


  <a href="#option-technique">
    <div id="option-description" data-controller="open-on-click">
      <button data-action="open-on-click#toggleDescription", class="description">Description du spot</button>
      <p data-open-on-click-target="description", class="open hidden"><%= @spot.description %></p>
    </div>
  </a>

<a href="#option-danger">
  <div id="option-technique" data-controller="open-on-click">
    <button data-action="open-on-click#toggleDescription", class="description">Zone technique</button>
    <p data-open-on-click-target="description", class="open hidden"><%= @spot.technique %></p>
  </div>
</a>

<a href="#option-danger">
  <div id="option-danger" data-controller="open-on-click">
    <button data-action="open-on-click#toggleDescription", class="description">Danger</button>
    <p data-open-on-click-target="description", class="open hidden"><%= @spot.danger %></p>
  </div>
</a>